"""Weather metadata and staging layers tables added

Revision ID: 1e5c74851888
Revises: 
Create Date: 2026-05-31 06:08:52.267437

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1e5c74851888'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_raw_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('city_name', sa.Text(), nullable=False),
    sa.Column('minio_link', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(precision=53), nullable=False),
    sa.Column('longitude', sa.Float(precision=53), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('s3_bucket', sa.Text(), nullable=False),
    sa.Column('response_bytes', sa.Integer(), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('dag_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_raw_log')),
    schema='metadata'
    )
    op.create_index(op.f('ix_weather_raw_log_dag_id'), 'weather_raw_log', ['dag_id'], unique=False, schema='metadata', postgresql_using='hash')
    op.create_index(op.f('ix_weather_raw_log_run_id'), 'weather_raw_log', ['run_id'], unique=False, schema='metadata')
    op.create_table('weather_hourly',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('city_name', sa.Text(), nullable=False),
    sa.Column('observation_time', sa.DateTime(), nullable=False),
    sa.Column('temperature_2m', sa.Float(precision=53), nullable=True),
    sa.Column('temperature_measure', sa.Text(), nullable=False),
    sa.Column('source_s3_bucket', sa.Text(), nullable=True),
    sa.Column('source_s3_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('load_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['load_id'], ['metadata.weather_raw_log.id'], name=op.f('fk_weather_hourly_load_id_weather_raw_log')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_hourly')),
    sa.UniqueConstraint('city_name', 'observation_time', name=op.f('uq_weather_hourly_city_name_observation_time')),
    schema='stg'
    )
    op.create_index(op.f('ix_weather_hourly_city_name_observation_time'), 'weather_hourly', ['city_name', 'observation_time'], unique=False, schema='stg')
    op.drop_index(op.f('idx_dag_id'), table_name='weather_raw_log', postgresql_using='hash')
    op.drop_table('weather_raw_log')
    op.drop_index(op.f('idx_observation_time'), table_name='weather_hourly')
    op.drop_table('weather_hourly')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_hourly',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('city_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('observation_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('temperature_2m', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('temperature_measure', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_s3_bucket', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_s3_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('weather_hourly_pkey'))
    )
    op.create_index(op.f('idx_observation_time'), 'weather_hourly', ['observation_time'], unique=False)
    op.create_table('weather_raw_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('minio_link', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('city_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('s3_bucket', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('http_status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dag_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('weather_raw_log_pkey'))
    )
    op.create_index(op.f('idx_dag_id'), 'weather_raw_log', ['dag_id'], unique=False, postgresql_using='hash')
    op.drop_index(op.f('ix_weather_hourly_city_name_observation_time'), table_name='weather_hourly', schema='stg')
    op.drop_table('weather_hourly', schema='stg')
    op.drop_index(op.f('ix_weather_raw_log_run_id'), table_name='weather_raw_log', schema='metadata')
    op.drop_index(op.f('ix_weather_raw_log_dag_id'), table_name='weather_raw_log', schema='metadata', postgresql_using='hash')
    op.drop_table('weather_raw_log', schema='metadata')
    # ### end Alembic commands ###